/**
 * Incident Routes
 */

const express = require('express');
const { body, query } = require('express-validator');
const router = express.Router();
const { authenticate, authorize } = require('../middleware/auth');
const { validate } = require('../middleware/validate');
const {
    triggerSOS, listIncidents, getIncident, updateStatus, getTimeline, assignIncident
} = require('../controllers/incident.controller');

// POST /api/incidents/sos — SOS trigger (citizen + responder)
router.post('/sos', authenticate, [
    body('latitude').isFloat({ min: -90, max: 90 }),
    body('longitude').isFloat({ min: -180, max: 180 }),
    body('type').optional().isIn(['accident','medical','fire','cardiac','drowning','fall','assault','other']),
    body('aiCrashDetected').optional().isBoolean(),
    body('aiSeverityScore').optional().isFloat({ min: 0, max: 10 }),
    validate,
], triggerSOS);

// GET /api/incidents
router.get('/', authenticate, listIncidents);

// GET /api/incidents/:id
router.get('/:id', authenticate, getIncident);

// GET /api/incidents/:id/timeline
router.get('/:id/timeline', authenticate, getTimeline);

// POST /api/incidents/:id/assign — Responder self-assigns to an incident
router.post('/:id/assign', authenticate, authorize('responder'), assignIncident);

// PUT /api/incidents/:id/status — Admin/coordinator/hospital_staff update
router.put('/:id/status', authenticate, authorize('responder','hospital_staff','admin','coordinator'), [
    body('status').isIn(['en_route','arrived','transporting','resolved','cancelled','false_alarm','assigned']),
    validate,
], updateStatus);

// PATCH /api/incidents/:id/status — Alias used by mobile responder app
router.patch('/:id/status', authenticate, authorize('responder','hospital_staff','admin','coordinator'), [
    body('status').isIn(['en_route','arrived','transporting','resolved','cancelled','false_alarm','assigned']),
    validate,
], updateStatus);

// POST /api/incidents/web-sos — Unauthenticated web-based SOS (rate-limited by app.js SOS limiter)
// Creates incident with a guest/anonymous reporter, broadcasts via socket
router.post('/web-sos', [
    body('type').optional().isIn(['accident','medical','fire','cardiac','drowning','fall','assault','other']),
    body('latitude').optional().isFloat({ min: -90, max: 90 }),
    body('longitude').optional().isFloat({ min: -180, max: 180 }),
    validate,
], async (req, res, next) => {
    try {
        const { query: dbQuery } = require('../config/database');
        const { getSocketIO } = require('../websocket/socketManager');
        const { sendSMS } = require('../services/sms.service');
        const logger = require('../config/logger');

        const {
            type = 'other',
            latitude = null,
            longitude = null,
            description = '',
            landmark = '',
            manual_address = '',
            caller_phone = '',
            source = 'web',
        } = req.body;

        // Use 0,0 as a sentinel for unknown location
        const lat = latitude || 0.0;
        const lng = longitude || 0.0;

        // Create incident — incident_number auto-generated by DB trigger
        const result = await dbQuery(
            `INSERT INTO incidents (
                type, severity, status,
                latitude, longitude, address, landmark,
                description, reporter_id, is_anonymous
            ) VALUES ($1, 'unknown', 'reported', $2, $3, $4, $5, $6, NULL, TRUE)
            RETURNING id, incident_number, type, status, created_at`,
            [
                type, lat, lng,
                manual_address, landmark || manual_address,
                description || `Web SOS — ${type}${caller_phone ? ` · Callback: ${caller_phone}` : ''}`,
            ]
        );
        const incident = result.rows[0];

        // Log creation event
        await dbQuery(
            `INSERT INTO incident_events (incident_id, event_type, actor_id, actor_role, description)
             VALUES ($1, 'created', NULL, 'public', $2)`,
            [incident.id, `Web SOS submitted from browser (source: ${source})`]
        );

        // Broadcast to responders
        const io = getSocketIO();
        if (io) {
            io.to('responders').emit('incident:new', {
                ...incident,
                webSos: true,
                callerPhone: caller_phone,
                manualAddress: manual_address,
            });
        }

        logger.info('Web SOS triggered', { incidentId: incident.id, type, lat: latitude, lng: longitude });

        // SMS dispatch center if phone configured
        if (caller_phone) {
            sendSMS(caller_phone,
                `SERS: Your emergency (${incidentNum}) has been registered. Help is on the way. Keep this line open.`
            ).catch(() => {});
        }

        res.status(201).json({
            success: true,
            data: {
                incident_number: incident.incident_number,
                id: incident.id,
                status: incident.status,
                message: 'Emergency registered. Responders have been alerted.',
            },
        });
    } catch (error) { next(error); }
});

module.exports = router;

